### ISSUE TITLE
Tried but without success

### ISSUE THREAD

**Issue by RazYang** [ivzave/matebook-linux#1]
My laptop is hz-w09. 
I Just put the patched dsdt.aml in `/usr/local/lib/firmware/acpi` and 99-acpi-tables.conf in `/etc/dracut.conf.d/` but with no luck. The power button and volume buttons are still not working at all.
By the way, is that `iasl -fe refs.txt -da dsdt.dat ssdt*.dat` rather than `iasl -fe refs.txt -da dsdt.dsl ssdt*.dsl`?

**Comment by ivzave** [comment]
Sure it should be `.dat` not `.dsl`, thanks. I've also added note about version increment (forgot to mention initially), could you check dsdt overriding with incremented version?

**Comment by RazYang** [comment]
Thanks!!! It works perfect. Now the only disappointment in this laptop is the broadcom driver...
there are progresses I got:
`brcmfmac4356-pcie.clm_blob` in `https://github.com/andrew997/cyw-fmac-fw/raw/master/brcmfmac4356-pcie.clm_blob`
`brcmfmac4356-pcie.txt` in `https://chromium.googlesource.com/chromiumos/third_party/linux-firmware/+/master/brcm/brcmfmac4356-pcie.txt?format=TEXT`
`BCM4354A2-0a5c-6420.hcd` in `https://github.com/winterheart/broadcom-bt-firmware/raw/master/brcm/BCM4356A2-0a5c-6420.hcd` (need to rename at present)

Maybe you should put these in your project so that others can fix missing files more easily.

**Comment by ivzave** [comment]
I didn't put firmware files in repository because I've read broadcom restricts redistribution of these files in binary form. However it's a good idea to mention needed steps and place some links so thanks for your suggestion.
BTW you don't need to download that `txt` file, it resides in efivars on the device.
Did you notice any effect using CLM blob?

**Comment by RazYang** [comment]
I just saw the missing files error in journal and dmesg. The truth is that I can not tell any difference.
Anyway, thanks a lot for the effort you have paid.

**Comment by airobots** [comment]
I have the same issue on HZ-W19.

I have followed the instructions, incremented the version in dsdt.dsl, put the dsdt.aml in /usr/local/lib/firmware/acpi, put 99-acpi-tables.conf in /etc/dracut.conf.d, but the buttons still do not work.

@Zzorz: how do you make it work?
